version: "3.9"

services:
  backend:
    build: ./backend
    container_name: qr-backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: qr-frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: qr-caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
